version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - DOMAIN=${DOMAIN}
    container_name: app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
